# Generated by Django 5.0.14 on 2025-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('VIN', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('productionYear', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('bankAccount', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=20, null=True)),
                ('LName', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ClientCars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(blank=True, max_length=30, null=True)),
                ('LName', models.CharField(blank=True, max_length=30, null=True)),
                ('empPosition', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(blank=True, null=True)),
                ('totalPrice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(blank=True, max_length=30, null=True)),
                ('servicePrice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ServiceParts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('sparePartID', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(blank=True, max_length=30, null=True)),
                ('partPrice', models.IntegerField(blank=True, null=True)),
                ('partQuantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SparePart',
                'managed': False,
            },
        ),
    ]
