# Generated by Django 5.0.14 on 2025-05-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('VIN', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('productionYear', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('bankAccount', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('empPosition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=30)),
                ('servicePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('sparePartID', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=30)),
                ('partPrice', models.IntegerField()),
                ('partQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('totalPrice', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.client')),
            ],
        ),
    ]
